#!/bin/bash
#Returns date in YYYYMMDD format.

display_help(){
   echo
   echo "$(basename $0) --> Returns date in YYYYMMDD format."
   echo
   echo "Usage: $(basename $0) [-h]"
   echo
   echo "   -h, 	Display this help dialogue"
}

# Read options, if any
while getopts h opt
do
   case $opt
      in
         h) display_help; exit 0;;
         *) display_help; exit 1;;
   esac
done

# Check if no arguments are given.
if [ "$#" -gt 0 ] ; then
    echo Error: Arguments not permitted.
    display_help
    exit 2
fi

date +%Y%m%d
